export const ADD_POKEMON = 'ADD_POKEMON';
export const ADD_POKEMON_BY_TYPE = 'ADD_POKEMON_BY_TYPE';
export const ADD_POKEMON_DETAIL = 'ADD_POKEMON_DETAIL';
export const FILTER_POKEMON_BY_TYPE = 'FILTER_POKEMON_BY_TYPE';
export const CLEAR_POKEMON_LIST = 'CLEAR_POKEMON_LIST';